# Installer les dépendances nécessaires
# -------------------------------------

FROM nodered/node-red:4.0.2

# Installer les dépendances nécessaires
RUN npm install --no-fund --no-audit \
    node-red-node-ping \
    node-red-dashboard \
    node-red-contrib-fs-ops

