FROM python:3.11-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive

# Installation GStreamer et outils de compilation
RUN apt-get update && apt-get install -y \
    git automake libtool pkg-config libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev libglib2.0-dev libjson-glib-dev \
    gtk-doc-tools libncursesw5-dev libdaemon-dev libjansson-dev \
    libsoup2.4-dev libedit-dev gstreamer1.0-tools \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly gstreamer1.0-libav \
    python3-gst-1.0 meson ninja-build \
    && rm -rf /var/lib/apt/lists/*

# Compilation gstd (comme dans ton script)
WORKDIR /tmp
RUN git clone https://github.com/RidgeRun/gstd-1.x.git && \
    cd gstd-1.x && \
    meson build --prefix=/usr/local && \
    ninja -C build install && \
    cd libgstc/python && \
    python3 setup.py install

# Installation paho-mqtt
RUN pip3 install --no-cache-dir paho-mqtt

# Copie du projet
WORKDIR /app
COPY . .

RUN chmod +x entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]